### ISSUE TITLE
非常棒，求扩展大模型生态厂商！

### ISSUE THREAD

**Issue by inksong** [log-z/logos#2]
chatglm已有
求扩展文心一言、百川、通义千问等国内大模型厂商！

**Comment by inksong** [comment]
另外有支持渠道吗！

**Comment by log-z** [comment]
@inksong 我发现有个更加完善的项目，你可以去看看，还挺多的。
[lobehub/lobe-icons](https://github.com/lobehub/lobe-icons)

**Comment by inksong** [comment]
thx!

log-z ***@***.***> 于2024年10月25日周五 22:21写道：
